// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Candidate struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Dob        string    `json:"dob"`
	BioLink    string    `json:"bio_link"`
	ImageUrl   string    `json:"image_url"`
	Policy     string    `json:"policy"`
	VoteCount  int32     `json:"vote_count"`
	Percentage int32     `json:"percentage"`
	CreateAt   time.Time `json:"create_at"`
}

type ElectionProperty struct {
	ID       int64     `json:"id"`
	Name     string    `json:"name"`
	Value    bool      `json:"value"`
	CreateAt time.Time `json:"create_at"`
}

type User struct {
	NationalID        string    `json:"national_id"`
	HashedPassword    string    `json:"hashed_password"`
	FullName          string    `json:"full_name"`
	Email             string    `json:"email"`
	Permission        []string  `json:"permission"`
	HasVoted          bool      `json:"has_voted"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreateAt          time.Time `json:"create_at"`
}

type Vote struct {
	ID             int64     `json:"id"`
	VoteNationalID string    `json:"vote_national_id"`
	CandidateID    int64     `json:"candidate_id"`
	CreateAt       time.Time `json:"create_at"`
}
