// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateCandidate(ctx context.Context, arg CreateCandidateParams) (Candidate, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVote(ctx context.Context, arg CreateVoteParams) (Vote, error)
	DeleteCandidate(ctx context.Context, id int64) error
	GetCandidate(ctx context.Context, id int64) (GetCandidateRow, error)
	GetElectionProperty(ctx context.Context, name string) (ElectionProperty, error)
	GetUser(ctx context.Context, nationalID string) (User, error)
	ListCandidates(ctx context.Context, arg ListCandidatesParams) ([]ListCandidatesRow, error)
	ListCandidatesResult(ctx context.Context) ([]ListCandidatesResultRow, error)
	ListVoteOrderByCandidate(ctx context.Context) ([]ListVoteOrderByCandidateRow, error)
	UpdateCandidate(ctx context.Context, arg UpdateCandidateParams) (UpdateCandidateRow, error)
	UpdateElectionProperty(ctx context.Context, arg UpdateElectionPropertyParams) (ElectionProperty, error)
}

var _ Querier = (*Queries)(nil)
